name: crypto_simple_example
description: Demonstrates how to use the crypto_simple plugin.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  crypto_simple:
    path: ../

flutter:
  uses-material-design: true
