name: crypto_simple
description: A library for encrypt and decrypt string , very light & simple and fast.
version: 2.0.0
repository: https://github.com/esmaeil-ahmadipour/crypto_simple
homepage: https://github.com/esmaeil-ahmadipour/crypto_simple

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
